# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'shibozou-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Research', folder: 'pages', file: 'research.html'}
- {name: 'Teaching', folder: 'pages', file: 'teaching.html'}
- {name: 'Mentoring', folder: 'pages', file: 'mentoring.html'}
- {name: 'Publications', folder: 'pages', file: 'publications.html'}
- {name: 'Media', folder: 'pages', file: 'media.html'}
- {name: 'About me', folder: 'pages', file: 'aboutme.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/ShiboZou'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/shibo-zou-2877747a/'}
- {icon: 'envelope', link: 'mailto:s.zou@amolf.nl'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
